.github/workflows/main.yml, README.md, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_eterms.h, c_src/quicer_listener.c, c_src/quicer_nif.c, c_src/quicer_queue.h, c_src/quicer_stream.c, c_src/quicer_stream.h, src/quicer.erl, src/quicer_nif.erl, src/quicer_stream.erl, test/quicer_SUITE.erl
Old passive recv API  buffers message in process heap which is a hack.
This PR utilizes msquic `StreamReceiveComplete` and `StreamReceiveSetEnabled` API to make quicer support real passive receive.
=> Real stream passive receive

c_src/quicer_connection.c, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_stream.c, test/quicer_SUITE.erl
- mark stream close in NIF ctx
- skip sending if conn/strm is in the middle of closing
=> avoid stream closing race

.github/workflows/main.yml, CMakeLists.txt
FIX issue #46 
- CI: don't use `jwlawson/actions-setup-cmake`
becasue github action virtual-environments has newer CMake 3.20.5 now
- Fix compiling error detect in CMake 3.20
=> Dev/william/fix compile with cmake 3.20.5

.github/workflows/main.yml, CMakeLists.txt, rebar.config
It provides lttng trace in the downloadable CommonTest log in case the CI is failed.
=> ci: wrap tests with lttng trace

.github/workflows/main.yml, CMakeLists.txt
Changes to adapt to new GitHub CI ubuntu-latest image.
- Update msquic.lttng debug lib outdir.
- Update to use lttng2.13
=> ci: lttng 2.13 and fix msquic.lttng outdir

src/quicer.erl, test/quicer_SUITE.erl
Not good idea to have conn retry in quicer.
Let application decide how and when to retry or just
fallback to TCP.
=> fix: remove conn timeout retry

src/quicer.app.src
The hex.pm package is missing the `pkgname.sh` script and currently fails with:
```bash
./build.sh: line 7: ./pkgname.sh: No such file or directory
make: *** [Makefile:11: build-nif] Error 1
===> Hook for compile failed!
** (Mix) Could not compile dependency :quicer, "/Users/kevin/.asdf/installs/elixir/ref-main/.mix/elixir/1-15/rebar3 bare compile --paths /Users/kevin/Documents/repos/bandit/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile quicer", update it with "mix deps.update quicer" or clean it with "mix deps.clean quicer"
```
=> Add missing `pkgname.sh` script

c_src/quicer_connection.c
It turns out that the Certificate pointer may be null then QUIC_CONNECTION_EVENT_PEER_CERTIFICATE_RECEIVED event is triggered.
=> Fixed potential segfault when certificate is a null pointer.

c_src/quicer_connection.c, docs/messages_to_owner.md, docs/todo.org, include/quicer_types.hrl, src/quicer.erl, src/quicer_connection.erl, src/quicer_lib.erl, src/quicer_server_conn_callback.erl, src/quicer_stream.erl, test/example_client_stream.erl, test/example_server_connection.erl, test/example_server_stream.erl, test/quicer_SUITE.erl, test/quicer_echo_server_stream_callback.erl, test/quicer_snb_SUITE.erl
- Orphan stream stay in passive mode before handoff to the new owner.
- Add post_handoff callback so prev owner could supply post hand off data to the new owner. 
- behaviors have new optional handle_call/handle_info/handle_continue callbacks.
=> feat(multi-streams): manageable  stream handoff

src/quicer.erl, test/quicer_SUITE.erl
fix #150
When sync conn API call is failed after conn start, the conn closed event is useless to the caller because the handle
will not be presented to the caller.  the closed event is just non interesting junk in the proc mailbox.
This PR flush it before returns to the caller.
No changes in NIF because for client, no conn closed event will be sent if handshake is failed.
=> fix(conn): flush closed event when sync conn fail

src/quicer_connection.erl, src/quicer_listener.erl, src/quicer_stream.erl
The signature for `gen_server:format_status` callback have changed in OTP-25. Instead of updating implementations to support both signatures it's better to drop them altogether since they are no-ops.
Also remove few unused macrodefs.
=> chore: drop noop optional callbacks impls

c_src/quicer_connection.c, c_src/quicer_connection.h, c_src/quicer_nif.c, src/quicer.erl, src/quicer_nif.erl, test/quicer_snb_SUITE.erl
- New API open_connection/0 for testing.
- Deprecated the method of resuming a connection from the old conn handle.
=> feat(api): quicer:open_connection/0

src/quicer_local_stream.erl, src/quicer_remote_stream.erl, src/quicer_server_conn_callback.erl, test/example_server_connection.erl, test/quicer_SUITE.erl, test/quicer_echo_server_stream_callback.erl, test/quicer_snb_SUITE.erl, test/quicer_test_lib.erl
mem check tool reports some indirect mem leak due to
- some owner process is not stopped in some testcase
- some connection isn't aborted after test
- some uninterested signals from quic are not consumed from mailbox of CT process.
=> fix resource leaks in test

c_src/quicer_nif.c, test/quicer_SUITE.erl
After controlling_process/2 call, the old owner is demonitored *asynchronously*. That is we may get a stream/conn resource_down callback with the pid of old owner while the new ower is already set in the resource ctx.
This change double check if the resource owner is the dead process pid and shutdown the resource only when they match.
=> fix(resource_down):  double check ownership

test/example/p_connect.lux, test/example/qt.erl
To reproduce, run 
```
cd  test/example
make all
lux p_connect.lux
```
=> Bug with controlling_process for Connection

c_src/quicer_config.c, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_listener.c, c_src/quicer_listener.h, c_src/quicer_nif.c, src/quicer.erl, src/quicer_nif.erl, test/quicer_SUITE.erl, test/quicer_snb_SUITE.erl
Improve listener API,
- add API to stop and restart the listener with Listener handle
- fix config resource leaks in listener
- rename start_listener to spawn listener for supervised listener
- rename stop_listener to terminate listener for supervised listener
=> feat: stop then start listener

c_src/quicer_config.c, c_src/quicer_config.h, c_src/quicer_connection.c, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_listener.c, test/quicer_SUITE.erl, test/quicer_snb_SUITE.erl
while accepting new conn, the listener no longer creates trusted store per connection that should reduce per-connection resource usage.
=> perf(tls): share trusted store

.github/workflows/main.yml, CMakeLists.txt, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_nif.c, c_src/quicer_nif.h, c_src/quicer_reg.c, c_src/quicer_reg.h, include/quicer_types.hrl, src/quicer.erl, src/quicer_nif.erl, test/quicer_SUITE.erl, test/quicer_reg_SUITE.erl, test/quicer_snb_SUITE.erl
msquic registration is an abstraction of execution env (threads)
Currently, all quicer resources use one global registration. 
This PR add multi-registration support for mapping msquic registration to quicer.
There will be follow-up PRS to
1. server: create listener under certain registration 
2. client: create new connection under certain registraion 
3. global registraion list that keeps track of the registration used by quicer.
=> support multi execution registrations 

Makefile, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_listener.c, c_src/quicer_listener.h, c_src/quicer_nif.c, c_src/quicer_reg.c, src/quicer.erl, src/quicer_nif.erl, test/quicer_SUITE.erl, test/quicer_listener_SUITE.erl
- Track listeners in registration.
-  New API quicer:get_listeners/0,1
=> track listeners in registration

c_src/quicer_config.c, c_src/quicer_connection.c, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_stream.c, c_src/quicer_stream.h, test/quicer_SUITE.erl
=> feat: cache stream id

c_src/quicer_connection.c, c_src/quicer_connection.h, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_listener.c, c_src/quicer_nif.c, src/quicer.erl, src/quicer_nif.erl, test/quicer_connection_SUITE.erl
=> feat: list connections under registration

c_src/quicer_connection.c, test/quicer_snb_SUITE.erl
without this change, peer will get stream send/recv aborted as we return an error (QUIC_STATUS_UNREACHABLE) to the callback if picked the owner who is dead.
=> feat: dead stream acceptor fallback to conn owner

c_src/quicer_eterms.h, c_src/quicer_nif.c, c_src/quicer_reg.c, docs/messages_to_owner.md, include/quicer_types.hrl, src/quicer_connection.erl, test/example_client_connection.erl, test/example_server_connection.erl, test/quicer_connection_SUITE.erl, test/quicer_test_lib.erl
- add dgram recv callback
- fixing naming of datagram -> dgram
- fix some confusion perf profile naming
=> feat: add dgram recv callback

.github/workflows/cover.yaml, CMakeLists.txt, c_src/quicer_connection.c, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_listener.c, c_src/quicer_nif.c, c_src/quicer_tls.c, test/quicer_connection_SUITE.erl, test/quicer_snb_SUITE.erl
fix #250 
This is new feature in msquic 2.2.
Before this change certificate (chain) validation was done in the callback (quicer) , now it is done in TLS.
- The old method is wrapped with `QUICER_USE_TRUSTED_STORE`
We used to have trusted store cache in listener to speed up handshakes.
- more tweaks for macOS to make it work
=> Set cacertfile in tls ctx

c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_listener.c, c_src/quicer_nif.c, c_src/quicer_tls.c, c_src/quicer_tls.h, src/quicer_listener.erl, test/quicer_SUITE.erl, test/quicer_listener_SUITE.erl
- remove cacertfile from l_ctx
- new "cred config" builder function
=> refactor: QUIC cred config

src/quicer_listener.erl, test/quicer_listener_SUITE.erl
Our user want to get conn counts per listener, it is not supported in msquic.
So I add this workaround in Erlang.
=> feat(listener): count connections under listener

c_src/quicer_config.c, c_src/quicer_connection.c, c_src/quicer_listener.c, c_src/quicer_tls.c
Fix mem leaks detected by proper tests.
They are all negative cases when invalid tls configs are failed to set but some object like intermediate string (from Erlang term to string)  is not released.
=> fix mem leaks with invalid TLS configs

Makefile, c_src/quicer_connection.c, test/prop_stateful_client_conn.erl, tools/asan/bin/sanitizer-check
Catched by proper tests,
In `quicer:get_connections` call, while holding the lock of `r_ctx`, deref `c_ctx` may cause connection close and then trigger callback that destroy `c_ctx` which try to lock `r_ctx` in another thread, causing dead lock.
solution is to deref `c_ctx` after unlock r_ctx.
=> fix dead lock while get connecions

c_src/quicer_listener.c, c_src/quicer_nif.c
=> fix: hanging registration close due to a race in listener stop/close

c_src/quicer_connection.c, include/quicer_types.hrl, test/example_client_connection.erl, test/example_server_connection.erl, test/example_server_stream.erl, test/prop_quic_types.hrl, test/prop_stateful_stream.erl, test/quicer_snb_SUITE.erl
fix #281
- add stream proper tests
- fix `s_ctx` leaks when stream acceptor is dead
=> memleak dead acceptor

src/quicer.erl, test/prop_stateful_client_conn.erl, test/prop_stateful_server_conn.erl, test/prop_stateful_stream.erl, test/quicer_SUITE.erl
=> apply default stream start flag

Makefile, c_src/quicer_config.c, c_src/quicer_config.h, c_src/quicer_connection.c, test/quicer_SUITE.erl, test/quicer_listener_SUITE.erl
lets move on to msquic 2.3.5
maybe fixed #285
=> msquic2.3.5

CMakeLists.txt, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_nif.c, c_src/quicer_owner_queue.c, c_src/quicer_owner_queue.h, c_src/quicer_stream.c, c_src/quicer_stream.h, src/quicer.erl, src/quicer_nif.erl, test/example_client_connection.erl, test/prop_stream_sig_queue.erl
QUIC stream data is ensured ordered and lossless during stream handoff from old owner process to the new owner process.
This PR makes QUIC stream signals also ordered so that old owner does not need to take care of the `inflight` messages during the handoff.
The new `quicer_owner_queue` things could be reused to later implement the sig queues for the quic connections.
=> buffer stream signals

get-msquic.sh
I get a "*** buffer overflow detected ***" crash when I run the latest Ubuntu release. I suspect this has to do with some changes in glibc that makes it better at detecting potential buffer overruns.
The fix below from msquic solves the problem.
=> Apply buffer overwrite fix from later msquic builds.

build.sh
Downside is it won't be upgradable.
=> build: remove dup dyn lib files for EMQX build

.gitmodules, get-msquic.sh
relates to #261 
Adding submodule/msquic will help us identify and address potential vulnerabilities in the code.
=> Add submodule msquic

c_src/quicer_stream.c
prefer to inspect binary first because inspect binary as iolist alloc and copies the binary which has high memory footprint
=> perf: prefer inspect binary to avoid copy

c_src/quicer_nif.c, c_src/quicer_tp.c, c_src/quicer_tp.h, src/quicer_nif.erl, test/quicer_snb_SUITE.erl
fix lock_order_violation when run with debug emu type
````
at beam/erl_lock_check.c:1225
at beam/erl_threads.h:1991
````
debug emu doesn't like to call enif_whereis_pid in resource down callback.
=> test: use global_snab_kc_pid

c_src/quicer_connection.c, c_src/quicer_listener.c, c_src/quicer_stream.c, c_src/quicer_tp.c, test/example_client_connection.erl, test/prop_stateful_client_conn.erl, test/prop_stateful_server_conn.erl, test/quicer_connection_SUITE.erl, tools/run/bin/lib.sh
- add support for monitoring remote stream
- fix some proper tests.
- more safe trace points in tests.
=> feat: monitor remote stream

c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_nif.c, src/quicer_nif.erl, test/quicer_SUITE.erl
- quicer_nif:copy_stream_handle/1
- quicer_nif:malloc_trim/0
- quicer_nif:malloc_stats/0
=> feat(tools): add some mem related toolings (internal)

.github/workflows/release.yaml
EMQX needs this prebuild as EMQX by default links to sys libcrypto
=> ci(release): release macos links to sys libcrypto

get-msquic.sh
quick fix: #334
- buffer overflow when tracing
- buffer overflow when GSO off, Linux epoll, large payload https://github.com/microsoft/msquic/pull/4717
=> fix: apply more patches for msquic 2.3.8

.github/workflows/codeql.yml, .github/workflows/cover.yaml, .github/workflows/lux.yml, .github/workflows/main.yml, .github/workflows/release.yaml, test/quicer_test_lib.erl
Another notable change to the release workflow is an ability to re-release existing tags through the _workflow dispatch_ trigger. This could be useful to populate existing releases with binaries built for recent Erlang/OTP versions (in this case Erlang/OTP 27).
See individual commits for details.
=> ci: switch workflows to recent Erlang/OTP 27

c_src/quicer_connection.c, c_src/quicer_ctx.c, c_src/quicer_ctx.h, c_src/quicer_listener.c, c_src/quicer_tls.c, c_src/quicer_tls.h, test/quicer_SUITE.erl
fix #336 
port #337 to main branch
=> feat: new listener opt: sslkeylogfile

c_src/quicer_nif.c
Hi! I've been compiling and running quicer on alpine, but recent versions no longer compile. I'm a little bit out of my depth here but it seems to be because alpine uses musl instead of glibc and is missing the malloc_trim and malloc_stats functions. These are already protected by the __linux__ define so I'm wondering if you would consider changing that to __GLIBC__ instead.
=> Guard glibc-specific functions using __GLIBC__ define

get-msquic.sh, msquic_patches/12edf3725475d4a99e5598df3289bace47b8f56e.patch, msquic_patches/9261dacc1dd9a67f6fa8d5fbe663082508b4c605.patch, msquic_patches/README.md, msquic_patches/b16a14a72e8c74407ee4a079a1f57efe0246f739.patch, msquic_patches/e0201eb4e007e7524aef007be67f2281f949f102.patch
to handle github HTTP 429 resp while downloading the patches.
```
curl: (22) The requested URL returned error: 429
```
EMQX CI failed due to downloading msquic patches, this caches the patches in quicer source tree
=> build: cache patches

c_src/quicer_connection.c, test/quicer_connection_SUITE.erl
This PR enables SSL key log file dumping even when connection verification fails, allowing for debugging of failed TLS handshakes. The change moves the SSL key dumping logic from the successful connection handler to the connection destruction handlers, ensuring secrets are written regardless of connection outcome.
Refactored SSL key log dumping into a reusable safe_dump_conn_tls_secrets function
Added SSL key dumping to both client and server connection destruction paths
Added test case to verify SSL key log file creation when peer verification fails
=> feat: dump sslkeylogfile even conn fail

.github/workflows/main.yml, src/quicer.erl, src/quicer_nif.erl
fix [EEC-951](https://emqx.atlassian.net/browse/EEC-951)
By setting QUICER_NO_NIF=1,
NIF module (quicer_nif) will be loaded successfully, and quicer
application could be started but NONE of the functions can work.
This is used in some deployment that the quicer functions are not
required/desired but quicer app is embedded in release that requires
it to start successfully.
=> feat: runtime envvar kill switch QUICER_NO_NIF

src/quicer_app.erl, src/quicer_nif.erl
EMQX 5 booting get blocking if kill switch is enabled as io blocking. 
The reason is unknown,  it may due to the embeded mode or `noshell`? 
(rebar3 shell was tested without getting blocked)
NOTE: Does not work with EMQX 6 with mix build.
=> fix: prevent warnings of kill switch blocking the boot process.
