emqx/quic

c_src/quicer_config.c
c_src/quicer_connection.c
c_src/quicer_ctx.c
c_src/quicer_nif.c
c_src/quicer_nif.h
c_src/quicer_queue.c
c_src/quicer_queue.h
c_src/quicer_stream.c

v1.0.0 does not support MacOS.

Bring latest msquic

---

Makefile
c_src/quicer_config.c
test/quicer_SUITE.erl

Support getstat on stream but fallback to getstat on connection.

feat(api): quicer:getstat/2 part 2

---

c_src/quicer_config.c
c_src/quicer_config.h
c_src/quicer_connection.c
c_src/quicer_eterms.h
c_src/quicer_listener.c
c_src/quicer_nif.c
c_src/quicer_nif.h
src/quicer.erl
test/quicer_SUITE.erl

enable
`quicer:listen(Port, [{alpn, ["sample2", "sample"]}])` then
`quicer:connect("localhost", Port, [{alpn, "sample"}], 5000)`

parameterize alpn in connect/4 and listen/2

---

c_src/quicer_config.c
c_src/quicer_config.h
c_src/quicer_nif.h
test/quicer_SUITE.erl

check if I am in a right direction. If ok, I'll add remaining client configs.

feat(connect): set config thru opts

---

.github/workflows/main.yml

30m to 10m, though we cannot specify minor version.

test(ci): use brew to prepare erlang

---

README.md
src/quicer.erl
test/quicer_SUITE.erl

- Update README
- make quicer:getstat/2 following inet:getstat/2

fix(doc): Update docs

---

README.md
c_src/quicer_config.c
c_src/quicer_connection.c
c_src/quicer_ctx.c
c_src/quicer_listener.c
c_src/quicer_nif.c
c_src/quicer_queue.c
c_src/quicer_queue.h
c_src/quicer_stream.c
src/quicer.erl
test/quicer_SUITE.erl

- receiving side connection flow control 
- handle opts of accept connection call

connection flow control 

---

.github/workflows/main.yml
c_src/quicer_config.c
c_src/quicer_stream.c
test/quicer_SUITE.erl

fix: arm support

---

.gitmodules
CMakeLists.txt
get-msquic.sh
rebar.config

My download speed is like 4MB/s:
before:
```
________________________________________________________
Executed in  188.59 secs   fish           external
usr time  101.48 secs    1.79 millis  101.48 secs
sys time   27.20 secs    0.28 millis   27.20 secs
```
after:
```
________________________________________________________
Executed in   53.13 secs   fish           external
usr time   13.61 secs  713.00 micros   13.61 secs
sys time    6.12 secs   48.00 micros    6.12 secs
```

chore: change to shallow clone of msquic and all its submodules

---

c_src/quicer_connection.c
c_src/quicer_ctx.c
c_src/quicer_ctx.h
c_src/quicer_listener.c
c_src/quicer_nif.c
c_src/quicer_stream.c
c_src/quicer_tp.c
c_src/quicer_tp.h
src/quicer.erl
src/quicer_stream.erl
test/quicer_snb_SUITE.erl

- zero copy send
-  fix some binary leakage
- Stream immediate shutdown when stream owner is dead

perf: zero copy send

---

test/quicer_snb_SUITE.erl

test: fix a flaky snk testcase

---

src/quicer_nif.erl

Remove file_server dependency, use file nif instead
fix #80

chore: support early start

---

.github/workflows/release.yaml
.gitignore
Makefile
build.sh
pkgname.sh
rebar.config
src/quicer_nif.erl

build and release binary packages per `OTP_VERSION-OS-ARCH`

feat: release binary packages

---

.github/workflows/main.yml
src/quicer.app.src
src/quicer.erl
test/quicer_snb_SUITE.erl

Export async connect and also retry connect

---

c_src/quicer_config.c

fix: missing MtuDiscoverySearchCompleteTimeoutUs

---

c_src/quicer_config.c
c_src/quicer_ctx.c
c_src/quicer_ctx.h
c_src/quicer_stream.c
docs/internals.org
src/quicer.erl
test/quicer_SUITE.erl
test/quicer_snb_SUITE.erl

No dup recv complete call in passive recv

---

.github/workflows/main.yml
c_src/quicer_config.c
c_src/quicer_stream.c
test/quicer_snb_SUITE.erl

enable recvcallback when no recv pending

---

.github/workflows/cover.yaml
.github/workflows/hex_pub.yml
.github/workflows/main.yml
c_src/quicer_config.c
c_src/quicer_connection.c
c_src/quicer_stream.c
docs/DesignDecisions.md
test/quicer_SUITE.erl

- fix issue that could cause dbg NIF crash by enforcing the message coping.
- fixed CI OS version to ubuntu 20.04
- fix one minor issue found by Github code scanning.

fix: enforce message copy to the owner msg box

---

src/quicer_connection.erl

- peer_needs_streams
- nst_received

chore(quicer_connection): mark optional callbacks

---

c_src/quicer_nif.c
c_src/quicer_stream.c
c_src/quicer_stream.h
docs/messages_to_owner.md
include/quicer.hrl
src/quicer.erl
src/quicer_local_stream.erl
src/quicer_nif.erl
src/quicer_remote_stream.erl
src/quicer_stream.erl
test/quicer_SUITE.erl
test/quicer_snb_SUITE.erl

- support low overhead sending data over new stream in connection.
- support 0-RTT data

Impl. direct send 

---

include/quicer_types.hrl
src/quicer.erl
test/example/Makefile
test/example/qt.erl
test/example/rev.erl

Found a few type errors in the quicer code as well. Especially, the cacert stuff must be part of listen opts for the server

Dialyzer work on test/example

---

.github/workflows/lux.yml

ci: run lux examples

---

README.md
build.sh

build: fix macOS M1 code sign issue

---

src/quicer.erl
test/quicer_SUITE.erl

feat(api): quicer:negotiated_protocol/1

---

include/quicer_types.hrl
test/quicer_snb_SUITE.erl

test: stream abortive shutdown

---

get-msquic.sh

fix: patch msquic 2.2.3 for global lb config

---

rebar.config
tools/asan/bin/sanitizer-check

chore: bump snabbkaffe 1.0.10

---

CMakeLists.txt
build.sh

logging variant rel package should be helpful for debugging.

build: release logging variant

---

src/quicer.erl

remove dead code and update spec.

chore: remove dead code and fix spec

---

.github/workflows/codeql.yml
.github/workflows/cover.yaml
.github/workflows/lux.yml
.github/workflows/main.yml
.github/workflows/release.yaml
test/quicer_test_lib.erl

ci: enable CI + releases targeting recent Erlang/OTP 27

---

.github/workflows/release.yaml

cherry pick https://github.com/emqx/quic/pull/344

ci(release): use github-runner arm64

---

.github/workflows/lux.yml
.github/workflows/main.yml
.github/workflows/release.yaml

Use latest builder version, add missing operating systems

ci: update release workflow

---

build.sh

backport #378 to branch  main-0.1

build(macos): adapt to cmake 4 (#378)
